mail:
  # conf for email sending to amdin
  admin:
    to: jeffreycaizhenyuan@gmail.com
    from: bluestreamjc@tpg.com.au
    mailer: smtp
    SMTPSecure: tls
    host: mail.tpg.com.au
    port: 587
    username: bluestreamjc@tpg.com.au
    nickname: My TPG Mailbox
    password: Monday01
  
  # general conf for site-wide emails
  general:
    reply_to: jeffreycaizhenyuan@gmail.com
    from: ozboxoffice@gmail.com
    from_nickname: 代购喵
    mailer: smtp
    SMTPSecure: tls
    host: smtp.mandrillapp.com
    port: 587
    username: jeangirl186@163.com
    password: bHw0jZxX9Kb4QrMqIYY-fg