routing:
  index:
    path: ^\/?$
    isSecure: 0
    i18n: 1
    controller: site/index
    static_cache: 9999
    
  panel_dashboard:
    path: ^\/panel\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/dashboard
  panel_affiliator_order:
    path: ^\/panel\/affiliator\/order\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/order
  panel_user_profile:
    path: ^\/panel\/user\/profile\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/user/profile
  panel_admin_product_list:
    path: ^\/panel\/admin\/product\/list\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/admin/product_list
  panel_admin_product_add:
    path: ^\/panel\/admin\/product\/add\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/admin/product_add
  panel_admin_product_edit:
    path: ^\/panel\/admin\/product\/(\d+)\/edit\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/admin/product_edit
  panel_admin_product_delelte:
    path: ^\/panel\/admin\/product\/(\d+)\/delete\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/admin/product_delete
  panel_admin_subproduct_edit:
    path: ^\/panel\/admin\/product\/(\d+)\/list\/?$
    isSecure: 0
    i18n: 1
    controller: site/panel/admin/subproduct_edit
    


assets:
  frontend:
    css:
      # bootstrap
      bootstrap:
        path: .?
        position: top
        weight: 10
#        source: //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css
        source: site/assets/css/bootstrap.min.css
      # fontawesome
      fontawesome:
        path: .?
        position: top
        weight: 20
        source: //maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css
      # toastr: notification
      toastr:
        path: .?
        position: top
        weight: 30
        source: site/assets/css/plugins/toastr/toastr.min.css
      # global default
      default_style:
        path: .?
        position: top
        weight: 290
        source: site/assets/css/style.css
      # global custom
      panel_style:
        path: .?
        position: top
        weight: 300
        source: site/assets/panel_style.css
      site_style:
        path: .?
        position: top
        weight: 400
        source: site/assets/site_style.css
        
        
        
    js:
      bootstrap:
        path: .?
        position: bottom
        weight: 10
#        source: //netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js
        source: site/assets/js/bootstrap.min.js
      metisMenu:
        path: .?
        position: bottom
        weight: 20
        source: core/assets/js/metisMenu/jquery.metisMenu.js
      toastr:
        path: .?
        position: bottom
        weight: 30
        source: site/assets/js/plugins/toastr/toastr.min.js
#      moltin:
#        path: .?
#        position: top
#        weight: 10
#        source: //js.moltin.com/v1
      panel_script:
        path: .?
        position: bottom
        weight: 300
        source: site/assets/panel_script.js
        