product:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    title: VARCHAR(512) NOT NULL
    description: TEXT
    active: TINYINT(1) DEFAULT 1
    price: DECIMAL(6,1) DEFAULT 0
    thumbnail: VARCHAR(15)

sub_product:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    product_id: INT NOT NULL
    attribute: VARCHAR(32) NOT NULL
    price: DECIMAL(6,1) DEFAULT NULL
    active: TINYINT(1) DEFAULT 1
  fks:
    product_id:
      foreign_key: product_id
      references: product.id
      on_delete: CASCADE
      on_update: CASCADE
    
    
item:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    original_id: INT
    title_en: VARCHAR(512)
    title_zh: VARCHAR(512)
    thumbnail: VARCHAR(256)
    price: VARCHAR(6)
    updated_at: INT
  indexes:
    - `item_original_id` (`original_id` ASC)
    
item_category:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    item_id: INT
    category_id: INT
  fks:
    category_id:
      foreign_key: category_id
      references: category.id
      on_delete: CASCADE
      on_update: CASCADE
    item_id:
      foreign_key: item_id
      references: item.id
      on_delete: CASCADE
      on_update: CASCADE