product:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    title: VARCHAR(512) NOT NULL
    description: TEXT
    active: TINYINT(1) DEFAULT 1
    price: DECIMAL(6,1) DEFAULT 0
    thumbnail: VARCHAR(15)

sub_product:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    product_id: INT NOT NULL
    attribute: VARCHAR(32) NOT NULL
    price: DECIMAL(6,1) DEFAULT NULL
    active: TINYINT(1) DEFAULT 1
  fks:
    product_id:
      foreign_key: product_id
      references: product.id
      on_delete: CASCADE
      on_update: CASCADE
    
    
item:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    original_id: INT
    title_en: VARCHAR(512)
    title_zh: VARCHAR(512)
    thumbnail: VARCHAR(256)
    price: VARCHAR(6)
    updated_at: INT
    vendor_id: INT DEFAULT 1
    brand_id: INT DEFAULT 1
  fks:
    vendor_id:
      foreign_key: vendor_id
      references: vendor.id
      on_delete: CASCADE
      on_update: CASCADE
    brand_id:
      foreign_key: brand_id
      references: brand.id
      on_delete: CASCADE
      on_update: CASCADE
  indexes:
    - `item_original_id` (`original_id` ASC)
    

    
item_tag:
  pk: id
  fields:
    id: INT NOT NULL AUTO_INCREMENT
    item_id: INT
    tag_id: INT
  fks:
    tag_id:
      foreign_key: tag_id
      references: tag.id
      on_delete: CASCADE
      on_update: CASCADE
    item_id:
      foreign_key: item_id
      references: item.id
      on_delete: CASCADE
      on_update: CASCADE